{
 "title": "People Access Tracking",
 "time": { "from": "2021-11-03T10:44:13.000Z", "to": "2025-10-27T10:44:13.000Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Last Person Who Entered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: -0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")\r\n  |> filter(fn: (r) => r.event == \"entry\")\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r.epc  \r\n  }))\r\n  |> rename(columns: {_value: \"epc\"})  "
    }
   ]
  },
  {
   "title": "Latest movments",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 20)\r\n  |> keep(columns: [\"_time\", \"epc\", \"event\", \"door\", \"box\", \"_field\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      epc: string(v: r.epc),\r\n      event: string(v: r.event),\r\n      door: string(v: r.door),\r\n      box: string(v: r.box)\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Total Entry vs Total Exit",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> group(columns: [\"event\"])\r\n  |> count()\r\n  |> keep(columns: [\"event\", \"_value\"])\r\n  |> rename(columns: {_value: \"\"})\r\n"
    }
   ]
  },
  {
   "title": "Door x Entry/Exit",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")\r\n  |> filter(fn: (r) => r.event == \"entry\" or r.event == \"exit\")\r\n  |> group(columns: [\"door\", \"event\"])\r\n  |> count()\r\n  |> pivot(rowKey: [\"door\"], columnKey: [\"event\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      door: r.door,\r\n      entry: if exists r.entry then r.entry else 0,\r\n      exit: if exists r.exit then r.exit else 0,\r\n      total: (if exists r.entry then r.entry else 0) + (if exists r.exit then r.exit else 0)\r\n  }))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Top 3 Most active People",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")  // pick a single numeric field\r\n  |> group(columns: [\"epc\"])\r\n  |> count()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 3)\r\n  |> keep(columns: [\"epc\", \"_value\"])\r\n  |> rename(columns: {_value: \"Event Count\"})\r\n"
    }
   ]
  },
  {
   "title": "Last seen per Person",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"rfid_events\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"rfid_event\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")\r\n  |> group(columns: [\"epc\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> group()\r\n  |> keep(columns: [\"epc\", \"_time\"])\r\n"
    }
   ]
  }
 ]
}